// ── Discord OAuth2 Config ─────────────────────────────────────────────────────
// The client_secret lives ONLY on the server (server/.env).
// Only safe-to-expose values go here.

module.exports = {
  clientId:     '1480999494639419575',
  redirectUri:  'http://localhost:7355/callback',
  callbackPort: 7355,

  // URL of your deployed auth server (change after deploying)
  serverUrl: 'https://your-auth-server.railway.app',

  // RSA public key — generated by: cd server && node generate-keys.js
  // Paste the contents of server/public.pem here (replace this placeholder).
  publicKey: `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqeWoTGLR5pvj3hKVMD4C
ungs8Ux349aFPL06BbTciSfbBI8iCP7IeAIhqMPjCoEOhIFWmIKr0xhCG6moKs/0
cSdvYlD27QGiuDX6NZBaaeMpl3nX2FgrUk2EttoEVmj2u+4L6HQgqMlPhGnmRK+s
mr+3YxzhA5d3ilX1O29IKWvd4MzQUQDD+D4uhF0bjIEsEUT63kn4b6xMYO/TRYyt
PtS9P/qWkLbwKUflavof7vpcIW0N913/nsM32OfNhUy3//ET1qiZwK1gIkhc2605
sNXc/RLbOGf4Pu57lTTQjbJ5zG9rDueD//EzoBVBDECWk2AVMm50x562zFhg9anA
uQIDAQAB
-----END PUBLIC KEY-----`,
}
